### PR TITLE
Add azure blob storage header to patch

### LINKED ISSUE #600: Screenshots not uploading to Azure Storage
Please note - issues that are not following the template will be closed automatically:

- [ x] I have verified that all sorry-cypress services are running and accessible
- [ x] I have read documentation and found no answer to my problem
- [ x] I have searched issues / discussions and found to answer to my problem
- [ x] I have read [Minio Configutation guide](https://docs.sorry-cypress.dev/configuration/director-configuration/minio-configuration) - for issues related to Screenshots / Videos uploads for Minio 
- [ x] I have activated the debug mode `DEBUG=cypress:server:api cy2 ....` and have the network error

## Summary

Required header `x-ms-blob-type` is not being set when uploading screenshots to Azure Storage

## How to reproduce

1. Provision azure storage account
2. Use new azure screenshots driver
3. Execute cypress tests in debug mode

```
'StatusCodeError: 400 - "<?xml version=\\"1.0\\" encoding=\\"utf-8\\"?>\\n<Error><Code>MissingRequiredHeader</Code><Message>An HTTP header that&apos;s mandatory for this request is not specified.\\nRequestId:629f8e17-601e-0022-3517-95da9a000000\\nTime:2022-07-11T11:16:48.5754318Z</Message><HeaderName>x-ms-blob-type</HeaderName>
```
Full stack trace: https://gist.github.com/IanMoroney/ae978defe37b7f5b8a01fd689ab6b2d4

According to the [Microsoft documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#request-headers-all-blob-types), this header is required.

## Environment

- sorry-cypress version: 2.1.6
- cypress version: `9.7.0`
- platform: `kubernetes via helm`
- service: `director`

### PR DESCRIPTION
**Pull request by Hackatosh**
Closes https://github.com/sorry-cypress/sorry-cypress/issues/600

### CODE REVIEW

**Comment by agoldis** [comment]
@Hackatosh please let me know when it's ready for review. I have created an npm org for sorry-cypress and want to grant you publish permissions for this package. Do you have an npm account?

**Comment by IanMoroney** [comment]
So i've tested this locally and i'm having a problem with it.

I've pulled down @Hackatosh's source, compiled it and installed it locally into my project, and I get an error when trying to find upload.js:

```
npx cy2-azure run -e TAGS="@focus" --record --key keygoeshere  --ci-build-id b1 --group GR1 --browser chrome
Error: ENOENT: no such file or directory, copyfile '/Users/work/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/upload.js ' -> '/Users/work/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/_upload.js '
    at Object.copyFileSync (node:fs:2800:3)
    at Object.<anonymous> (/Users/work/Source/Repos/b2c/testproject/e2e/cy2-azure/dist/patch.js:66:25)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/work/Source/Repos/b2c/testproject/e2e/cy2-azure/dist/patch.js:15:28)
    at _next (/Users/work/Source/Repos/b2c/testproject/e2e/cy2-azure/dist/patch.js:33:17) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '/Users/work/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/upload.js ',
  dest: '/Users/work/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/_upload.js '
}
```

The weird thing is, `/Users/work/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/upload.js` does actually exist:

```
ls -al /Users/work/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/upload.js
-rw-r--r--  1 work  staff  292 23 May 16:35 /Users/work/Library/Caches/Cypress/9.7.0/Cypress.app/Contents/Resources/app/packages/server/lib/upload.js
```
I've tried:
`npm cache clean --force`
`npm uninstall ./cy2-azure`
`npm install --save ./cy2-azure`
Remove `node_modules`
`npm i`

and still get the same issue.

Are you able to replicate this issue when trying to use `cy2-azure` to execute some tests?

**Comment by Hackatosh** [comment]
@agoldis I have created an npm account with the username hackatosh
@IanMoroney Sorry you ran into an error, I did not have the time yet to test this. I'll try to see what the problem is

**Comment by IanMoroney** [comment]
@Hackatosh, it works!
I ran your package locally, did a `cy2-azure` run pointed at sorry-cypress, and it did take screenshots, upload them into azure storage, and display them in the test results!

**Comment by IanMoroney** [comment]
There does seem to be a bug with the uploader though where I think it's trying to upload too fast.
In a test suite with 16 tests, once the tests have completed, and the screenshots are being uploaded, all 16 are trying to be pushed at once, which I think hits a rate limit.

my nginx instance in front of the sorry-cypress director reports:

```
We encountered an unexpected error talking to our servers.

We will retry 3 more times in 30 seconds...

The server's response was:

StatusCodeError: 502 - "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
```

And on the server side:
director-log:
```
022-07-21T14:49:26+01:00 AppError: AppError
2022-07-21T14:49:26+01:00     at Object.setScreenshotUrl (/app/packages/director/src/execution/mongo/instances/instance.controller.ts:33:11)
2022-07-21T14:49:26+01:00     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
2022-07-21T14:49:26+01:00   code: 'SCREENSHOT_URL_UPDATE_FAILED'
2022-07-21T14:49:26+01:00 }
2022-07-21T14:49:26+01:00 AppError: AppError
2022-07-21T14:49:26+01:00     at Object.setScreenshotUrl (/app/packages/director/src/execution/mongo/instances/instance.controller.ts:33:11)
2022-07-21T14:49:26+01:00     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
2022-07-21T14:49:26+01:00   code: 'SCREENSHOT_URL_UPDATE_FAILED'
2022-07-21T14:49:26+01:00 } unhandledRejection
2022-07-21T14:49:26+01:00 2022-07-21T13:49:26: PM2 log: App [dist:0] exited with code [1] via signal [SIGINT]
2022-07-21T14:49:26+01:00 2022-07-21T13:49:26: PM2 log: App [dist:0] starting in -fork mode-
2022-07-21T14:49:26+01:00 2022-07-21T13:49:26: PM2 log: App [dist:0] online
```

Maybe there should be a very very tiny delay between each screenshot upload?

**Comment by Hackatosh** [comment]
@agoldis I think this is ready for review ! I have added the tests and as said by @IanMoroney it correctly patches Cypress.

@IanMoroney I am not sure your problem is related to this PR. I think this problem is caused by this part of the code in Sorry Cypress in `packages/director/src/api/instances.ts` line 196 :
` screenshotUploadUrls.forEach((screenshot: ScreenshotUploadInstruction) => {
      executionDriver.setScreenshotUrl(
        instanceId,
        screenshot.screenshotId,
        screenshot.readUrl
      );
    });`


Sorry Cypress is doing an async operation (setScreenshotUrl) which then throw an error which is not caught (since it's not awaited) and that's why you have an unhandledRejection error.  In your case, it seems that having an unhandled rejection kills your server. As the backend is down, you have a 502 error on NGINX side.

Did you experience this problem while using a difference kind of storage (S3, minio, etc) ?

**Comment by IanMoroney** [comment]
Sadly, i've not been able to try another storage backend, so i'm not sure if it's repeatable there.

**Review by IanMoroney — APPROVED** [review]

**Comment by IanMoroney** [comment]
@Hackatosh , actually there's one more change required in terms of setting headers.
The `content-type` header needs to be set, as images are uploaded to azure storage as `application/octet-stream`.

**Comment by IanMoroney** [comment]
```
blobHTTPHeaders: { blobContentType: 'image/png' }
```

**Comment by Hackatosh** [comment]
@IanMoroney What is the problem exactly if you do not set the content type ?

I think the content type should be set directly on Sorry Cypress side (it can be !) and not on the runner side, since it will not be the same between the screenshot upload and the video upload

Edit : I made a PR for that : https://github.com/sorry-cypress/sorry-cypress/pull/606

**Review by agoldis — APPROVED** [review]

**Comment by IanMoroney** [comment]
just checking @Hackatosh , is `cy2-azure` published to npm yet? would love to put this into our project :)

**Comment by agoldis** [comment]
https://www.npmjs.com/package/cy2-azure

**Comment by IanMoroney** [comment]
https://www.npmjs.com/package/cy2-azure

Well done!

Looks like it's not added to the search index yet so you can't actually search for the package but.

**Pull request merged**
